import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const COLORS = {
  primary: "#0f766e",
  primaryDark: "#0b5c56",
  primaryTint: "#ccfbf1",
  accent: "#c2410c",
  bg: "#f0fdfa",
  card: "#ffffff",
  border: "#cbe8e4",
  foreground: "#134e4a",
  muted: "#475569",
  mutedLight: "#94a3b8",
  white: "#ffffff",
};

const PAGE_MARGIN = 48;
const HEADER_HEIGHT = 104;
const FOOTER_HEIGHT = 46;

let logoBuffer = null;
try {
  logoBuffer = fs.readFileSync(path.join(process.cwd(), "public", "logo.png"));
} catch {
  logoBuffer = null;
}

function drawLogoBadge(doc, x, y, size) {
  doc.save();
  doc.circle(x + size / 2, y + size / 2, size / 2).fill(COLORS.white);
  if (logoBuffer) {
    doc.save();
    doc.circle(x + size / 2, y + size / 2, size / 2 - 3).clip();
    doc.image(logoBuffer, x + 3, y + 3, { width: size - 6, height: size - 6 });
    doc.restore();
  }
  doc.restore();
}

function drawClockIcon(doc, cx, cy, r, color) {
  doc.save();
  doc.lineWidth(1.1).strokeColor(color);
  doc.circle(cx, cy, r).stroke();
  doc.moveTo(cx, cy).lineTo(cx, cy - r + 2).stroke();
  doc.moveTo(cx, cy).lineTo(cx + r - 3, cy + 1).stroke();
  doc.restore();
}

function drawHeaderBanner(doc) {
  const pageWidth = doc.page.width;

  doc.rect(0, 0, pageWidth, HEADER_HEIGHT).fill(COLORS.primary);
  doc.rect(0, HEADER_HEIGHT - 4, pageWidth, 4).fill(COLORS.primaryDark);

  const logoSize = 46;
  const logoX = PAGE_MARGIN;
  const logoY = (HEADER_HEIGHT - logoSize) / 2;
  drawLogoBadge(doc, logoX, logoY, logoSize);

  const textX = logoX + logoSize + 14;
  const textWidth = pageWidth - textX - PAGE_MARGIN;

  doc
    .font("Helvetica-Bold")
    .fontSize(19)
    .fillColor(COLORS.white)
    .text("Donkey's Timetable", textX, logoY + 2, { width: textWidth });
  doc
    .font("Helvetica")
    .fontSize(9.5)
    .fillColor(COLORS.primaryTint)
    .text("Your schedule, organized.", textX, doc.y + 2, { width: textWidth });
}

function drawTitleBlock(doc, { timetableName, dateLabel }) {
  const pageWidth = doc.page.width;
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  let y = HEADER_HEIGHT + 26;

  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(COLORS.accent)
    .text("TIMETABLE", PAGE_MARGIN, y, { characterSpacing: 1.5 });
  y += 15;

  doc
    .font("Helvetica-Bold")
    .fontSize(23)
    .fillColor(COLORS.foreground)
    .text(timetableName, PAGE_MARGIN, y, { width: contentWidth });
  y = doc.y + 12;

  doc.font("Helvetica-Bold").fontSize(11);
  const pillText = dateLabel;
  const pillTextWidth = doc.widthOfString(pillText);
  const pillWidth = pillTextWidth + 30;
  const pillHeight = 25;
  doc.roundedRect(PAGE_MARGIN, y, pillWidth, pillHeight, 12.5).fill(COLORS.bg);
  doc
    .fillColor(COLORS.primary)
    .text(pillText, PAGE_MARGIN + 15, y + 7);
  y += pillHeight + 22;

  doc
    .moveTo(PAGE_MARGIN, y)
    .lineTo(pageWidth - PAGE_MARGIN, y)
    .lineWidth(1)
    .strokeColor(COLORS.border)
    .stroke();
  y += 22;

  return y;
}

function drawFooter(doc, pageNumber, totalPages) {
  const pageWidth = doc.page.width;
  const y = doc.page.height - FOOTER_HEIGHT + 8;

  doc
    .moveTo(PAGE_MARGIN, y)
    .lineTo(pageWidth - PAGE_MARGIN, y)
    .lineWidth(0.75)
    .strokeColor(COLORS.border)
    .stroke();

  const generatedAt = new Date().toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(COLORS.mutedLight)
    .text(`Generated by Donkey's Timetable  ·  ${generatedAt}`, PAGE_MARGIN, y + 10, {
      width: pageWidth - PAGE_MARGIN * 2 - 70,
    });

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(COLORS.mutedLight)
    .text(`Page ${pageNumber} of ${totalPages}`, pageWidth - PAGE_MARGIN - 70, y + 10, {
      width: 70,
      align: "right",
    });
}

// Picks a visual density (font sizes, spacing, whether notes/icons fit) so any
// subject count renders on exactly one A4 page instead of spilling to a new page.
function densityConfig(rowHeight) {
  if (rowHeight >= 84) {
    return { nameFont: 13.5, timeFont: 10, noteFont: 9.5, noteLines: 2, icon: true, badge: true, card: true, badgeR: 14, pad: 14 };
  }
  if (rowHeight >= 62) {
    return { nameFont: 12.5, timeFont: 9.5, noteFont: 9, noteLines: 1, icon: true, badge: true, card: true, badgeR: 12, pad: 11 };
  }
  if (rowHeight >= 40) {
    return { nameFont: 11.5, timeFont: 9, noteFont: 0, noteLines: 0, icon: true, badge: true, card: true, badgeR: 10, pad: 8 };
  }
  if (rowHeight >= 22) {
    return { nameFont: 10, timeFont: 8.5, noteFont: 0, noteLines: 0, icon: false, badge: true, card: true, badgeR: 8, pad: 5 };
  }
  return { nameFont: 8.5, timeFont: 8, noteFont: 0, noteLines: 0, icon: false, badge: false, card: false, badgeR: 0, pad: 3 };
}

function drawRow(doc, subject, index, x, y, width, height, cfg) {
  if (cfg.card) {
    doc.roundedRect(x, y, width, height, Math.min(10, height / 4)).fillAndStroke(COLORS.card, COLORS.border);
    doc.roundedRect(x, y, 4, height, 2).fill(COLORS.accent);
  } else {
    doc
      .moveTo(x, y + height)
      .lineTo(x + width, y + height)
      .lineWidth(0.5)
      .strokeColor(COLORS.border)
      .stroke();
  }

  let textX;
  if (cfg.badge) {
    const bx = x + 14 + cfg.badgeR;
    const by = y + height / 2;
    doc.circle(bx, by, cfg.badgeR).fill(COLORS.primary);
    const badgeFont = Math.max(7, cfg.badgeR * 0.78);
    doc
      .font("Helvetica-Bold")
      .fontSize(badgeFont)
      .fillColor(COLORS.white)
      .text(String(index + 1), bx - cfg.badgeR, by - badgeFont / 2, { width: cfg.badgeR * 2, align: "center" });
    textX = x + 14 + cfg.badgeR * 2 + 10;
  } else if (cfg.card) {
    textX = x + 16;
  } else {
    doc
      .font("Helvetica-Bold")
      .fontSize(cfg.nameFont)
      .fillColor(COLORS.primary)
      .text(`${index + 1}.`, x, y + (height - cfg.nameFont) / 2, { width: 18 });
    textX = x + 20;
  }

  const rightPad = cfg.card ? 16 : 6;
  const textWidth = x + width - rightPad - textX;

  // Dense / ultra: single line, name and time share the row.
  if (!cfg.icon && cfg.noteLines === 0) {
    const rowY = y + (height - cfg.nameFont) / 2;
    const timeWidth = subject.time ? Math.min(110, textWidth * 0.4) : 0;
    doc
      .font("Helvetica-Bold")
      .fontSize(cfg.nameFont)
      .fillColor(COLORS.foreground)
      .text(subject.name, textX, rowY, {
        width: textWidth - timeWidth - (subject.time ? 8 : 0),
        height: cfg.nameFont + 2,
        ellipsis: true,
        lineBreak: false,
      });
    if (subject.time) {
      doc
        .font("Helvetica")
        .fontSize(cfg.timeFont)
        .fillColor(COLORS.muted)
        .text(subject.time, x + width - rightPad - timeWidth, rowY, {
          width: timeWidth,
          height: cfg.timeFont + 2,
          align: "right",
          ellipsis: true,
          lineBreak: false,
        });
    }
    return;
  }

  // Spacious / comfortable / compact: name, then time, then optional note.
  let ty = y + cfg.pad;
  doc
    .font("Helvetica-Bold")
    .fontSize(cfg.nameFont)
    .fillColor(COLORS.foreground)
    .text(subject.name, textX, ty, { width: textWidth, height: cfg.nameFont + 3, ellipsis: true, lineBreak: false });
  ty += cfg.nameFont + 6;

  if (subject.time) {
    if (cfg.icon) {
      drawClockIcon(doc, textX + 4, ty + cfg.timeFont * 0.55, 4, COLORS.primary);
      doc
        .font("Helvetica")
        .fontSize(cfg.timeFont)
        .fillColor(COLORS.muted)
        .text(subject.time, textX + 13, ty, { width: textWidth - 13, height: cfg.timeFont + 2, ellipsis: true, lineBreak: false });
    } else {
      doc
        .font("Helvetica")
        .fontSize(cfg.timeFont)
        .fillColor(COLORS.muted)
        .text(subject.time, textX, ty, { width: textWidth, height: cfg.timeFont + 2, ellipsis: true, lineBreak: false });
    }
    ty += cfg.timeFont + 6;
  }

  if (cfg.noteLines > 0 && subject.note) {
    doc
      .font("Helvetica-Oblique")
      .fontSize(cfg.noteFont)
      .fillColor(COLORS.mutedLight)
      .text(subject.note, textX, ty, { width: textWidth, height: cfg.noteFont * 1.3 * cfg.noteLines, ellipsis: true });
  }
}

function drawEmptyState(doc, y, contentWidth) {
  const pageWidth = doc.page.width;
  const iconSize = 60;
  const cx = pageWidth / 2;
  const iconY = y + 30;

  doc.roundedRect(cx - iconSize / 2, iconY, iconSize, iconSize, 12).fillAndStroke(COLORS.bg, COLORS.border);
  doc.roundedRect(cx - iconSize / 2, iconY, iconSize, 16, 12).fill(COLORS.primary);
  doc.rect(cx - iconSize / 2, iconY + 8, iconSize, 8).fill(COLORS.primary);
  doc.circle(cx - iconSize / 2 + 15, iconY, 2.5).fill(COLORS.white);
  doc.circle(cx + iconSize / 2 - 15, iconY, 2.5).fill(COLORS.white);

  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(COLORS.foreground)
    .text("No subjects added", PAGE_MARGIN, iconY + iconSize + 22, { width: contentWidth, align: "center" });
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(COLORS.mutedLight)
    .text("There are no subjects scheduled for this date yet.", PAGE_MARGIN, doc.y + 4, {
      width: contentWidth,
      align: "center",
    });
}

// Builds a beautifully branded PDF for one date's subjects, always fit onto a
// single A4 page: row height/fonts/detail level scale down as the subject
// count grows, instead of spilling onto extra pages.
export function generateDayPdf({ timetableName, dateLabel, subjects }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 0, bufferPages: true });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const contentWidth = doc.page.width - PAGE_MARGIN * 2;
    const bottomLimit = doc.page.height - FOOTER_HEIGHT - 16;

    drawHeaderBanner(doc);
    const startY = drawTitleBlock(doc, { timetableName, dateLabel });
    const available = Math.max(0, bottomLimit - startY);

    const list = subjects || [];
    if (list.length === 0) {
      drawEmptyState(doc, startY, contentWidth);
    } else {
      const n = list.length;
      const idealRowHeight = 90;
      const idealGap = 14;
      let rowHeight;
      let gap;

      if (idealRowHeight * n + idealGap * (n - 1) <= available) {
        rowHeight = idealRowHeight;
        gap = idealGap;
      } else {
        const gapRatio = 0.16;
        rowHeight = Math.max(12, available / (n + (n - 1) * gapRatio));
        gap = Math.max(2, rowHeight * gapRatio);
      }

      const totalHeight = n * rowHeight + (n - 1) * gap;
      const cfg = densityConfig(rowHeight);
      let y = startY + Math.max(0, (available - totalHeight) / 2);

      list.forEach((subject, i) => {
        drawRow(doc, subject, i, PAGE_MARGIN, y, contentWidth, rowHeight, cfg);
        y += rowHeight + gap;
      });
    }

    const range = doc.bufferedPageRange();
    const totalPages = range.count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      drawFooter(doc, i + 1, totalPages);
    }

    doc.end();
  });
}
